### ISSUE TITLE
Livenessprove doesn't give enough time to pod

### ISSUE THREAD

**Issue by willianpaixao** [immich-app/immich-charts#102]
Since v1.106.1, the merge between server and microservice containers made the new server container a lot heavier and the livenessprobe  has a threshold too low, not giving enough time for the container to properly start. So the container enters a CrashLoopBackOff cicle.

It took me a lot longer to find out because in the beginning the container has very little log and I was assuming it was a bug in the newer version.

I intend to write a PR next week, just wanted to give a heads up as soon as I found out.

**Comment by joaopedrocg27** [comment]
I modified my "server" as follows:

```
 server:
    enabled: true
    probes:
      liveness:
        spec:
          initialDelaySeconds: 120
      readiness:
        spec:
          initialDelaySeconds: 120
    resources:
      requests:
        cpu: 500m
        memory: 500Mi
      limits:
        cpu: 3
        memory: 3Gi
```
