### ISSUE TITLE
Immich not completing startup on 1.106.4 using chart 0.7.0

### ISSUE THREAD

**Issue by btajuddin** [immich-app/immich-charts#103]
When I tried to upgrade to Immich 1.106.4, I couldn't get the server to start properly. When I logged into the container, it was not even listening on port 3001, only 8081 and 8082. I've dug around a bit in the Immich code, but I'm not seeing exactly what is broken.

This is all the logs I get:

```
Detected CPU Cores: 40
Starting api worker
Starting microservices worker
[Nest] 7 - 06/19/2024, 4:20:54 PM LOG [Microservices:EventRepository] Initialized websocket server
[Nest] 17 - 06/19/2024, 4:20:54 PM LOG [Api:EventRepository] Initialized websocket server
```

Values file:
```
env:
  DB_PASSWORD: [redacted]
  DB_HOSTNAME: postgres-rw
  REDIS_HOSTNAME: redis-master


machine-learning:
  resources:
    requests:
      cpu: "2"
      memory: 4Gi
  persistence:
    cache:
      type: pvc
      storageClass: longhorn
  probes:
    liveness:
      spec:
        periodSeconds: 60

immich:
  metrics:
    enabled: false
  persistence:
    library:
      existingClaim: immich

postgresql:
  enabled: false

redis:
  enabled: false

server:
  resources:
    requests:
      cpu: "2"
      memory: 4Gi
  service:
    main:
      annotations:
        tailscale.com/expose: "true"
```
