### ISSUE TITLE
Deployment is waiting for PostgreSQL PVC

### ISSUE THREAD

**Issue by telometto** [immich-app/immich-charts#106]
Hi!

I am sorry if this is a dumb question, but do I need to create a separate PVC for Postgres, too, in addition to the one for the library? If yes, how do I reference it in the `values.yaml` file?
I am new to Helm, as I usually write the deployment files myself.

This is the output:
```
LAST SEEN   TYPE      REASON              OBJECT                                           MESSAGE
31s         Normal    ScalingReplicaSet   deployment/immich-machine-learning               Scaled up replica set immich-machine-learning-649797cc58 to 1
31s         Normal    ScalingReplicaSet   deployment/immich-server                         Scaled up replica set immich-server-68584ddd55 to 1
30s         Normal    SuccessfulCreate    replicaset/immich-server-68584ddd55              Created pod: immich-server-68584ddd55-jh2p8
30s         Normal    SuccessfulCreate    replicaset/immich-machine-learning-649797cc58    Created pod: immich-machine-learning-649797cc58-rfmj9
30s         Normal    Scheduled           pod/immich-server-68584ddd55-jh2p8               Successfully assigned immich/immich-server-68584ddd55-jh2p8 to homeserver
30s         Normal    Scheduled           pod/immich-machine-learning-649797cc58-rfmj9     Successfully assigned immich/immich-machine-learning-649797cc58-rfmj9 to homeserver
30s         Normal    SuccessfulCreate    statefulset/immich-postgresql                    create Claim data-immich-postgresql-0 Pod immich-postgresql-0 in StatefulSet immich-postgresql success
30s         Normal    SuccessfulCreate    statefulset/immich-postgresql                    create Pod immich-postgresql-0 in StatefulSet immich-postgresql successful
30s         Warning   FailedScheduling    pod/immich-postgresql-0                          0/1 nodes are available: pod has unbound immediate PersistentVolumeClaims. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling.
28s         Normal    Pulling             pod/immich-server-68584ddd55-jh2p8               Pulling image "ghcr.io/immich-app/immich-server:v1.106.1"
27s         Normal    Pulling             pod/immich-machine-learning-649797cc58-rfmj9     Pulling image "ghcr.io/immich-app/immich-machine-learning:v1.106.1"
4s          Normal    FailedBinding       persistentvolumeclaim/data-immich-postgresql-0   no persistent volumes available for this claim and no storage class is set
```

**Comment by bo0tzz** [comment]
The chart should come with a pvc for postgres, but you can override that with your own if you prefer. Do you have a default storageClass set?

**Comment by telometto** [comment]
> The chart should come with a pvc for postgres, but you can override that with your own if you prefer. Do you have a default storageClass set?

Thank you for the reply! I deploy a storageClass, of which `immich-pvc-library` is a part of, but nothing besides that.

---

Here are the full configuration files:

### immich-values.yaml
```yaml
## This chart relies on the common library chart from bjw-s
## You can find it at https://github.com/bjw-s/helm-charts/tree/main/charts/library/common
## Refer there for more detail about the supported values

# These entries are shared between all the Immich components

env:
  REDIS_HOSTNAME: '{{ printf "%s-redis-master" .Release.Name }}'
  DB_HOSTNAME: "{{ .Release.Name }}-postgresql"
  DB_USERNAME: "{{ .Values.postgresql.global.postgresql.auth.username }}"
  DB_DATABASE_NAME: "{{ .Values.postgresql.global.postgresql.auth.database }}"
  # -- You should provide your own secret outside of this helm-chart and use `postgresql.global.postgresql.auth.existingSecret` to provide credentials to the postgresql instance
  DB_PASSWORD: "{{ .Values.postgresql.global.postgresql.auth.password }}"
  IMMICH_MACHINE_LEARNING_URL: '{{ printf "http://%s-machine-learning:3003" .Release.Name }}'

image:
  tag: v1.107.2

immich:
  metrics:
    # Enabling this will create the service monitors needed to monitor immich with the prometheus operator
    enabled: false
  persistence:
    # Main data store for all photos shared between different components.
    library:
      # Automatically creating the library volume is not supported by this chart
      # You have to specify an existing PVC to use
      existingClaim: immich-pvc-library
  # configuration is immich-config.json converted to yaml
  # ref: https://immich.app/docs/install/config-file/
  #
  configuration: {}
    # trash:
    #   enabled: false
    #   days: 30
    # storageTemplate:
    #   enabled: true
    #   template: "{{y}}/{{y}}-{{MM}}-{{dd}}/{{filename}}"

# Dependencies

postgresql:
  enabled: true # false
  image:
    repository: tensorchord/pgvecto-rs
    tag: pg14-v0.2.0
  global:
    postgresql:
      auth:
        username: immich
        database: immich
        password: immich
  primary:
    initdb:
      scripts:
        create-extensions.sql: |
          CREATE EXTENSION cube;
          CREATE EXTENSION earthdistance;
          CREATE EXTENSION vectors;

redis:
  enabled: true # false
  architecture: standalone
  auth:
    enabled: false

# Immich components

server:
  enabled: true
  image:
    repository: ghcr.io/immich-app/immich-server
    pullPolicy: IfNotPresent
  ingress:
    main:
      enabled: false
      annotations:
        # proxy-body-size is set to 0 to remove the body limit on file uploads
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
      hosts:
        - host: immich.local
          paths:
            - path: "/"
      tls: []

machine-learning:
  enabled: true
  image:
    repository: ghcr.io/immich-app/immich-machine-learning
    pullPolicy: IfNotPresent
  env:
    TRANSFORMERS_CACHE: /cache
  persistence:
    cache:
      enabled: true
      size: 10Gi
      # Optional: Set this to pvc to avoid downloading the ML models every start.
      type: emptyDir
      accessMode: ReadWriteMany
      # storageClass: your-class
```

### immich-sc.yaml
```yaml
---
apiVersion: "storage.k8s.io/v1"
kind: "StorageClass"
metadata:
  name: "immich-sc"
provisioner: "kubernetes.io/no-provisioner"
volumeBindingMode: "WaitForFirstConsumer"
reclaimPolicy: "Retain"
allowVolumeExpansion: true
```

### immich-storage.yaml
```yaml
---           
apiVersion: "v1"     
kind: "PersistentVolume"                 
metadata:  
  name: "immich-pv-library"        
spec:
  storageClassName: "immich-sc"
  capacity:      
    storage: "1Ti"            
  accessModes:
    - "ReadWriteOnce"                      
  persistentVolumeReclaimPolicy: "Retain"
  hostPath:
    path: "/tank/apps/immich/library"
                                                                               
---                   
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:             
  name: "immich-pvc-library"    
  namespace: "immich"                   
spec:
  storageClassName: "immich-sc"
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Ti"
  volumeName: "immich-pv-library"
```
