### ISSUE TITLE
Allow configuring securityContext for the immich-server

### ISSUE THREAD

**Issue by cjvirtucio87** [immich-app/immich-charts#112]
I have [Pod Security Admission](https://kubernetes.io/docs/concepts/security/pod-security-admission/) enabled in my environment. This means `securityContext` has to have specific configuration for every pod's containers:

```
W0818 15:33:11.560779   11673 warnings.go:70] would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "immich-server" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "immich-server" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "immich-server" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "immich-server" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
```

It'd be great if we could configure this on the container for the `immich-server` pod:

```yaml
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      runAsUser: 1000
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
```
