### ISSUE TITLE
GPU Support?

### ISSUE THREAD

**Issue by gentoorax** [immich-app/immich-charts#121]
Does this helm chart support any GPU use? I have nvidia GPUs on my nodes and use them for other deployments. I'm not sure how best to pass this request on through values.yaml however?

From my existing normal deployments I need to pass these through. I know I can pass the env through already but what about these resources?

```yaml
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: all
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: "compute,video,utility"
```

```yaml
          resources:
            limits:
              nvidia.com/gpu: 1
```
