### ISSUE TITLE
Immich Fails to Scan External Library due to Redis Crash

### ISSUE THREAD

**Issue by ImranR98** [immich-app/immich-charts#123]
When I try scanning a large external library, the Redis container crashes with no error and the scan fails. This doesn't happen with very small libraries.
I've never had this issue with Docker compose, so I assume it's a Helm chart or K8s issue.
Couldn't find anything about this online, any help is appreciated.

Immich server crash logs:
```
[Nest] 7  - 09/22/2024, 12:29:51 AM     LOG [Microservices:LibraryService] Refreshing library 1dc29aae-610a-484b-ab9a-051f6f74b2f3
[Nest] 7  - 09/22/2024, 12:29:59 AM   ERROR [Microservices:JobService] Unable to run job handler (library/library-refresh): AbortError: Command aborted due to connection close
[Nest] 7  - 09/22/2024, 12:29:59 AM   ERROR [Microservices:JobService] AbortError: Command aborted due to connection close
    at abortError (/usr/src/app/node_modules/ioredis/built/redis/event_handler.js:81:17)
    at abortIncompletePipelines (/usr/src/app/node_modules/ioredis/built/redis/event_handler.js:105:28)
    at Socket.<anonymous> (/usr/src/app/node_modules/ioredis/built/redis/event_handler.js:140:13)
    at Object.onceWrapper (node:events:634:26)
    at Socket.emit (node:events:519:28)
    at TCP.<anonymous> (node:net:339:12)
[Nest] 7  - 09/22/2024, 12:29:59 AM   ERROR [Microservices:JobService] Object:
{
  "id": "1dc29aae-610a-484b-ab9a-051f6f74b2f3",
  "refreshModifiedFiles": false,
  "refreshAllFiles": false
}

missing 'error' handler on this Redis client
missing 'error' handler on this Redis client
missing 'error' handler on this Redis client
missing 'error' handler on this Redis client
missing 'error' handler on this Redis client
missing 'error' handler on this Redis client
missing 'error' handler on this Redis client
missing 'error' handler on this Redis client
missing 'error' handler on this Redis client
missing 'error' handler on this Redis client
missing 'error' handler on this Redis client
missing 'error' handler on this Redis client
missing 'error' handler on this Redis client
missing 'error' handler on this Redis client
missing 'error' handler on this Redis client
missing 'error' handler on this Redis client
missing 'error' handler on this Redis client
missing 'error' handler on this Redis client
missing 'error' handler on this Redis client
missing 'error' handler on this Redis client
Error: connect ECONNREFUSED 10.102.123.89:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '10.102.123.89',
  port: 6379
}
```

Redis crash (no error message, just exits):
```
1:C 22 Sep 2024 00:30:00.057 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 22 Sep 2024 00:30:00.057 * Redis version=7.2.5, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 22 Sep 2024 00:30:00.057 * Configuration loaded
1:M 22 Sep 2024 00:30:00.058 * monotonic clock: POSIX clock_gettime
1:M 22 Sep 2024 00:30:00.059 * Running mode=standalone, port=6379.
1:M 22 Sep 2024 00:30:00.061 * Server initialized
1:M 22 Sep 2024 00:30:00.061 * Reading RDB base file on AOF loading...
1:M 22 Sep 2024 00:30:00.061 * Loading RDB produced by version 7.2.5
1:M 22 Sep 2024 00:30:00.061 * RDB age 11927 seconds
1:M 22 Sep 2024 00:30:00.061 * RDB memory usage when created 0.83 Mb
1:M 22 Sep 2024 00:30:00.061 * RDB is base AOF
1:M 22 Sep 2024 00:30:00.061 * Done loading RDB, keys loaded: 0, keys expired: 0.
1:M 22 Sep 2024 00:30:00.061 * DB loaded from base file appendonly.aof.1.base.rdb: 0.000 seconds
1:M 22 Sep 2024 00:30:00.252 * DB loaded from incr file appendonly.aof.1.incr.aof: 0.191 seconds
1:M 22 Sep 2024 00:30:00.252 * DB loaded from append only file: 0.191 seconds
1:M 22 Sep 2024 00:30:00.252 * Opening AOF incr file appendonly.aof.1.incr.aof on server start
1:M 22 Sep 2024 00:30:00.252 * Ready to accept connections tcp
```

`values.yaml` (used with `envsubst` for the variables):
```yaml
env:
  REDIS_HOSTNAME: '{{ printf "%s-redis-master" .Release.Name }}'
  DB_HOSTNAME: "{{ .Release.Name }}-postgresql"
  DB_USERNAME: "{{ .Values.postgresql.global.postgresql.auth.username }}"
  DB_DATABASE_NAME: "{{ .Values.postgresql.global.postgresql.auth.database }}"
  DB_PASSWORD: "{{ .Values.postgresql.global.postgresql.auth.password }}"
  IMMICH_MACHINE_LEARNING_URL: '{{ printf "http://%s-machine-learning:3003" .Release.Name }}'

image:
  tag: release

podSecurityContext: # I'd like all Immich state/media to be readable with my own UID
  fsGroup: $MY_UID
securityContext:
  runAsUser: $MY_UID
  runAsGroup: $MY_UID
  allowPrivilegeEscalation: false
  seLinuxOptions:
    type: spc_t # SELinux doesn't play well with K8s PVCs

immich:
  metrics:
    enabled: false
  persistence:
    library:
      existingClaim: immich-server-pvc
  configuration: {}

postgresql:
  enabled: true
  image:
    repository: tensorchord/pgvecto-rs
    tag: pg14-v0.2.0
  global:
    postgresql:
      auth:
        username: immich
        database: immich
        password: $IMMICH_DB_PASSWORD
  primary:
    initdb:
      scripts:
        create-extensions.sql: |
          CREATE EXTENSION cube;
          CREATE EXTENSION earthdistance;
          CREATE EXTENSION vectors;
    persistence:
      enabled: true
      existingClaim: immich-main-pvc
      subPath: "postgres"
    podSecurityContext:
      fsGroup: $MY_UID
    containerSecurityContext:
      runAsUser: $MY_UID
      runAsGroup: $MY_UID
      allowPrivilegeEscalation: false
      seLinuxOptions:
        type: spc_t # SELinux doesn't play well with K8s PVCs

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
  master:
    persistence:
      enabled: true
      existingClaim: immich-main-pvc
      subPath: "redis"
    podSecurityContext:
      fsGroup: $MY_UID
    containerSecurityContext:
      runAsUser: $MY_UID
      runAsGroup: $MY_UID
      allowPrivilegeEscalation: false
      seLinuxOptions:
        type: spc_t # SELinux doesn't play well with K8s PVCs

server:
  enabled: true
  env:
      DB_PASSWORD: $IMMICH_DB_PASSWORD
  image:
    repository: ghcr.io/immich-app/immich-server
    pullPolicy: Always
  ingress:
    main:
      enabled: false
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
      hosts:
        - host: immich.local
          paths:
            - path: "/"
      tls: []
  persistence:
    external:
      enabled: true
      existingClaim: main-media-pvc
      readOnly: false

machine-learning:
  enabled: true
  image:
    repository: ghcr.io/immich-app/immich-machine-learning
    pullPolicy: Always
  env:
    TRANSFORMERS_CACHE: /cache
  persistence:
    cache:
      enabled: true
      size: 10Gi
      type: emptyDir
      accessMode: ReadWriteMany
```

**Comment by bo0tzz** [comment]
This isn't a helm chart issue, the library scanning process used to be inefficient which was fixed in #7934 (v1.113.0). Since you're using the `release` tag with the default `imagePullPolicy: IfNotPresent`, you're probably not getting new versions of Immich. It'd be better to use an explicit version tag.

**Comment by ImranR98** [comment]
Thanks, I didn't realize my setup would result in not getting new versions. But wasn't not the cause of the error - I just set this up on Friday and confirmed that I'm on v1.115.0. I was able to fix it by adding these settings to `redis.master`:

```yaml
    resourcesPreset: 2xlarge
    livenessProbe:
      failureThreshold: 1360
    readinessProbe:
      failureThreshold: 1360
```

I guess the default setting is too low for the number of items I have? Or maybe my server is too slow. Either way problem solved.
