### ISSUE TITLE
proposal: Support Multiple External Storage Volumes in Immich Helm Chart

### ISSUE THREAD

**Issue by yinheli** [immich-app/immich-charts#136]
## Summary

Enhance the Immich Helm chart to support configuration of multiple external storage volumes, allowing users to easily integrate their existing storage solutions / exists library when deploying Immich in Kubernetes environments.

## Background

Immich supports External Library functionality, but the current Helm chart lacks options for configuring external storage volumes. Users with multiple storage solutions for their media libraries face difficulties when deploying Immich via Helm.

## Proposal

1. Add configuration options in `values.yaml` for multiple external storage volumes.
2. Provide documentation on how to use these new features.

**Comment by samholton** [comment]
This is supported via the common chart library that is being used  https://github.com/immich-app/immich-charts/blob/main/README.md?plain=1#L10)

https://bjw-s.github.io/helm-charts/docs/common-library/storage/types/persistentVolumeClaim/

**Comment by yinheli** [comment]
Thanks very much. I know how to configure it. Just supplement the content of values.yaml to add an external storage volume.

```yaml
server:
  # ....

+  persistence:
+    external:
+      enabled: true
+      accessMode: ReadWriteOnce
+      size: 100Gi
```

**Comment by mrsauravsahu** [comment]
I had an external existing pvc to use 

Actually the docs over at https://bjw-s.github.io/helm-charts/docs/common-library/storage/types/persistentVolumeClaim/ is incorrect, I'll raise a PR later but this is the right yaml to use

```yaml
  persistence:
    externals:
      enabled: true
      type: pvc <-- the type persistentVolumeClaim is incorrect 
      existingClaim: pvc-homelab-app-data-immich-externals
```
