### ISSUE TITLE
How to append "-openvino" to ML image name in order to use HW accel?

### ISSUE THREAD

**Issue by joaopedrocg27** [immich-app/immich-charts#138]
Hi!

I was able to make HW transcoding work by modifying the live yaml but I am not sure how this charts supports it.

<img width="593" alt="image" src="https://github.com/user-attachments/assets/63f1e568-40e0-4c1c-acd3-dde61cf7ad8a">
<img width="690" alt="image" src="https://github.com/user-attachments/assets/1c5aae77-235c-4814-bed4-e11fde5b178a">

**Comment by bo0tzz** [comment]
values.yaml:
```yaml
machine-learning:
  image:
    tag: v1.118.2-openvino
```

**Comment by joaopedrocg27** [comment]
But this way it will not use the global tag declaration right? I have configured renovate to look at the global one

**Comment by bo0tzz** [comment]
Correct, there's no way to combine the two. It'd be nice to have hwaccel support in the chart so you can just set a type to use and it handles appending the right tag as well as setting the container resources etc. I'll rename this issue to be a FR for that.

**Comment by bo0tzz** [comment]
I don't know how any of the hardware accel mappings work in kubernetes, so if people who are currently using it can post their values here for the different methods that'd be a useful reference.

**Comment by joaopedrocg27** [comment]
> Correct, there's no way to combine the two. It'd be nice to have hwaccel support in the chart so you can just set a type to use and it handles appending the right tag as well as setting the container resources etc. I'll rename this issue to be a FR for that.

That would be perfect! Thanks

**Comment by joaopedrocg27** [comment]
> I don't know how any of the hardware accel mappings work in kubernetes, so if people who are currently using it can post their values here for the different methods that'd be a useful reference.

Just for some more context, my setup is based on node-feature-discovery with intel operator and gpu plugin. I am able to just give it a request of `gpu.intel.com/i915: "1".` It can even share the GPU along multiple applications, which you cannot do via mounting the dev as a volume. I can investigate how this works in the background but I think that for this some string manipulation in the tag name is enough! 

```
 server:
    enabled: true
    securityContext: # not sure if it is needed
        privileged: true
    resources:
      requests:
        cpu: 300m
        memory: 300Mi
        gpu.intel.com/i915: "1"
      limits:
        cpu: 3
        memory: 3Gi
        gpu.intel.com/i915: "1"
```

If I do a `lspci` in the immich container I can see the GPU

**Comment by bo0tzz** [comment]
Adding it via a device plugin is definitely sufficient, no need for any manual dev mount stuff!

**Comment by Tokynet** [comment]
Any update on this?

**Comment by bo0tzz** [comment]
Nope, if there's updates they will be posted here.

**Comment by samholton** [comment]
This is how I'm running with openvino using node-feature-discovery

https://github.com/samholton/homelab/blob/main/apps/immich/helm-release.yaml#L18-L30

**Comment by bo0tzz** [comment]
As DRA is now coming up, I think supporting that would be the way to satisfy this issue.

**Comment by dr00tb** [comment]
Got DRA working like this:

```yaml
machine-learning:
  controllers:
    main:
      pod:
        resourceClaims:
        - name: intel-gpu-resource
          resourceClaimTemplateName: intel-gpu-claim
      containers:
        main:
          image:
            tag: v3.0.0-openvino
          resources:
            claims:
            - name: intel-gpu-resource
```
```yaml
apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  name: intel-gpu-claim
spec:
  spec:
    devices:
      requests:
      - name: gpu
        exactly:
          deviceClassName: gpu.intel.com
          allocationMode: ExactCount
          count: 1
```
