### ISSUE TITLE
postgres database issues after upgrading to 

### ISSUE THREAD

**Issue by rwlove** [immich-app/immich-charts#144]
I'm not exactly sure what triggered this problem, but I upgraded my chart as well as my image from somewhere around 0.8.2 to 0.8.3 and v1.118.0 to v1.119.0 and I'm now hitting this problem with pretty much every combination of chart and image that I've tried.

```
➜  ~ kubectl -n media logs immich-postgresql-0 -f
chmod: changing permissions of '/var/run/postgresql': Operation not permitted

PostgreSQL Database directory appears to contain a database; Skipping initialization

2024-11-11 15:13:32.890 UTC [1] FATAL:  could not write lock file "postmaster.pid": No space left on device
```

My suspicion is that it has something to do with a change in the implementation of `readOnlyRootFilesystem` when immich moved from bitnami postresql v13 to v16.

```
@@ -21,7 +21,7 @@ dependencies:
   - name: postgresql
     condition: postgresql.enabled
     repository: https://charts.bitnami.com/bitnami
-    version: 13.2.24
+    version: 16.0.0
```

```
    postgresql:
      enabled: true
      primary:
        containerSecurityContext:
          readOnlyRootFilesystem: false
```

**Comment by rwlove** [comment]
The bitnami chart update was between 0.7.2 and 0.8.0, so assuming this is my problem then my initial statement was wrong and this happened when I upgraded from 0.7.2 to 0.8.0. I'm going to try to roll-back to 0.7.2 now.

**Comment by rwlove** [comment]
Rolling back to 0.7.2 didn't make a difference.

**Comment by rwlove** [comment]
That doesn't seem to be the problem.

```
➜  ~ kubectl -n media get pods immich-postgresql-0 -o wide ; ssh root@worker3 df -h /
NAME                  READY   STATUS             RESTARTS       AGE   IP            NODE                         NOMINATED NODE   READINESS GATES
immich-postgresql-0   0/1     CrashLoopBackOff   46 (34s ago)   8h    10.42.5.142   worker3.thesteamedcrab.com   <none>           <none>
Filesystem      Size  Used Avail Use% Mounted on
/dev/nvme0n1p4  930G   43G  887G   5% /
```

I saw some stuff in the bitnami chart about changing default storage backends or settings or something, but I didn't have the time to chase down the details. I'll put some time in in the coming days.

**Comment by rwlove** [comment]
Rolling back to 0.7.0 has the same problem and I don't think the ceph volume is that problem because that maps to `/bitnami/postgresql`.

```
    Mounts:
      /bitnami/postgresql from data (rw)
      /dev/shm from dshm (rw)
      /docker-entrypoint-initdb.d/ from custom-init-scripts (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-gxf22 (ro)
```

I have many other charts/pods/containers running in my cluster and this is the only one that is a problem.

**Comment by bo0tzz** [comment]
I don't really have an insight into what's going wrong, sorry. That said, I'd suggest migrating off the bitnami postgres setup anyways as I'm planning to remove it from the chart (#129).

**Comment by rwlove** [comment]
I understand. I was having so many issues with using my CNPG instance because of the vector stuff so I moved to the embedded postgres, now I've hit this issue. I love immich, but I've really struggled with keeping a reliable postgres database.

I filed a bug against postgres, maybe someone can give me some pointers over there. https://github.com/bitnami/charts/issues/30441

Thanks for all your work @bo0tzz.

**Comment by alexyao2015** [comment]
Had the same issue and figured it out. There was a resource limit applied to the database pod which caused it to restart because the db used too many resources. Removed it from the statefulset and no longer had crash loops

**Comment by samholton** [comment]
> I understand. I was having so many issues with using my CNPG instance because of the vector stuff so I moved to the embedded postgres, now I've hit this issue. I love immich, but I've really struggled with keeping a reliable postgres database.
> 
> I filed a bug against postgres, maybe someone can give me some pointers over there. [bitnami/charts#30441](https://github.com/bitnami/charts/issues/30441)
> 
> Thanks for all your work @bo0tzz.

I was playing around with cnpg for Immich the other night, this is what I came up with

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-pg
  namespace: immich-test
spec:
  imageName: tensorchord/cloudnative-pgvecto-rs:16.5-v0.3.0
  instances: 1
  primaryUpdateStrategy: unsupervised
  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-db-secret
      postInitSQL:
        - ALTER USER immich WITH SUPERUSER;
        - ALTER SYSTEM SET search_path TO "$user", public, vectors;
        - CREATE EXTENSION IF NOT EXISTS "vectors";
  postgresql:
    shared_preload_libraries:
      - "vectors.so"
  storage:
    storageClass: longhorn
    size: 10Gi
```

**Comment by samholton** [comment]
> Had the same issue and figured it out. There was a resource limit applied to the database pod which caused it to restart because the db used too many resources. Removed it from the statefulset and no longer had crash loops

You can set the resources explicitly, or use `resourcesPreset` (https://github.com/bitnami/charts/blob/main/bitnami/common/templates/_resources.tpl#L15)

```yaml
    postgresql:
      enabled: true
      global:
        postgresql:
          auth:
            username: *db_user
            database: *db_database
            existingSecret: immich-secret
      primary:
        resourcesPreset: "large"
```
