### ISSUE TITLE
Gateway API support is broken - requires common library upgrade

### ISSUE THREAD

**Issue by kashalls** [immich-app/immich-charts#165]
The helmchart uses common v1.4.0. The current version as of writing this issue is 3.7.3 

Passing the following yaml in the chart to enable Gateway API support results in the following error message:
```yaml
    server:
      route:
        main:
          enabled: true
          hostnames: ["{{ .Release.Name }}.domain.com"]
          parentRefs:
            - name: internal
              namespace: kube-system
              sectionName: https
          rules:
            - backendRefs:
                - name: immich-server
                  port: *port
```
```
Helm upgrade failed for release immich/immich with chart immich@0.9.1: resource mapping not found for name: "immich-server" namespace: "" from "": no matches for kind "HTTPRoute" in version "gateway.networking.k8s.io/v1alpha2" ensure CRDs are installed first
```

`common v1.4.0` hardcodes the apiVersion of `v1alpha2` in https://github.com/bjw-s/helm-charts/blob/923ef40a39520979c98f354ea23963ee54f54433/charts/library/common/templates/classes/_route.tpl#L25 whereas the current version supports all 3 versions of the crd. It is impossible to downgrade the version of the crd (which is `gateway api v1.2.0`) as cilium requires v1.2.0 experimental.
