### ISSUE TITLE
server unable to resolve redis hostname

### ISSUE THREAD

**Issue by jonsch318** [immich-app/immich-charts#187]
The immich server does not seem to correctly query the kube dns. However I have created a debug ephemeral container in the pod which can correctly resolve the redis hostname. 
I wanted to deploy redis/valkey separately but both my and the built in cannot be resolved.

`values.yaml`:
```yaml
---
# yaml-language-server:$schema=none
image:
  tag: v1.132.0
serviceAccount:
  create: true
env:
  DB_URL:
    valueFrom:
      secretKeyRef:
        name: immich-pg-app
        key: uri
  # REDIS_HOSTNAME: immich-valkey-primary
  # REDIS_PORT: 6379
  REDIS_USERNAME:
    valueFrom:
      secretKeyRef:
        name: immich-valkey
        key: username
  REDIS_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: immich-valkey
        key: password
envFrom:
  - configMapRef:
      name: immich-cm
immich:
  metrics:
    enabled: true
  persistence:
    library:
      existingClaim: immich
server:
  enabled: true
  ingress:
    main:
      enabled: false
redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: true
    existingSecret: valkey-secret
machine-learning:
  enabled: true
  persistence:
    cache:
      enabled: true
      size: 10Gi
      type: pvc
      storageClass: longhorn-static
      accessMode: ReadWriteMany

```

Log: 
```
[...]
Error: getaddrinfo ENOTFOUND immich-redis-master
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26) {
  errno: -3007,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'immich-redis-master'
}
missing 'error' handler on this Redis client
Error: getaddrinfo ENOTFOUND immich-redis-master
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26) {
  errno: -3007,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'immich-redis-master'
}
missing 'error' handler on this Redis client
/usr/src/app/node_modules/ioredis/built/redis/event_handler.js:182
                    self.flushQueue(new errors_1.MaxRetriesPerRequestError(maxRetriesPerRequest));
                                    ^
MaxRetriesPerRequestError: Reached the max retries per request limit (which is 20). Refer to "maxRetriesPerRequest" option for details.
    at Socket.<anonymous> (/usr/src/app/node_modules/ioredis/built/redis/event_handler.js:182:37)
    at Object.onceWrapper (node:events:633:26)
    at Socket.emit (node:events:518:28)
    at TCP.<anonymous> (node:net:351:12)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
Node.js v22.14.0
Error: getaddrinfo ENOTFOUND immich-redis-master
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26) {
  errno: -3007,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'immich-redis-master'
}
api worker exited with code 1
```
