### ISSUE TITLE
Embedded Redis Chart default values to avoid OOMKilled

### ISSUE THREAD

**Issue by SimonStiil** [immich-app/immich-charts#202]
Have been setting up Immich on kubernetes. As part of that setup I started importing all of my historical images.

My kubernetes cluster is a 4 node ARM64 cluster 8 cores pr node and 16GB of ram (Turing Pi 2 with 4 RK1 modules). It is running other services but not that use a lot of memory or CPU.

But I very fast ran into crash loops due to OOMKilled Both for Immich and Redis. 
Digging a lot deeper into it I found the issue was Redis hitting the limits of the embedded helm chart which by default sets the size to "nano" which is:
```
"nano" (dict 
      "requests" (dict "cpu" "100m" "memory" "128Mi" "ephemeral-storage" "50Mi")
      "limits" (dict "cpu" "150m" "memory" "192Mi" "ephemeral-storage" "2Gi")
   )
```
And it hits the limit of 193Mb very fast. 

For the 80.000 images I set up for when doing scanning I hit around 500+mb. 
I ended up setting the chart to
```
  "small" (dict 
      "requests" (dict "cpu" "500m" "memory" "512Mi" "ephemeral-storage" "50Mi")
      "limits" (dict "cpu" "750m" "memory" "768Mi" "ephemeral-storage" "2Gi")
   )
```

The full configuration I used I my helm chart was:
```
    redis:
      enabled: true
      master:
        extraFlags:
          - "--maxmemory"
          - "750mb"
          - "--maxmemory-policy"
          - "volatile-lru"
        resourcesPreset: "small"
```

This is ofcause just the configuration I found worked to me. But thought it would be a good idea to add a default configuration for Redis for users to build upon. Also I don't know if the integration at all uses the expire field so "volatile" would make a difference. But just to avoid crashloops.
