### ISSUE TITLE
feat: support `immich-machine-learning` hwaccel tags

### ISSUE THREAD

**Issue by judahrand** [immich-app/immich-charts#203]
It would be nice to be able to specify which version of the `immich-machine-learning` image to use. Currently, a global `immich.tag` is specified but since the `immich` container doesn't have hwaccel versions (eg `-cuda`, `-openvino` etc.) the `machine-learning` block in `values.yaml` needs to be overridden with 

```yaml
machine-learning:
  image:
    tag: v1.132.3-openvino
```

This seems to defeat the purpose of having a single global `image.tag`. Perhaps an `immich.hwaccel` option could be added to the `values.yaml` which, if set, could add the correct addition to the `immich-machine-learning` tag?

So if the `values.yaml` looked like:

```yaml
immich:
  hwaccel: openvino
image:
  tag: v1.132.3
```

then `immich-machine-learning:v1.132.3-openvino` would be used of the machine learning deployment.
