### ISSUE TITLE
Add support for multipath for the different persistent folder

### ISSUE THREAD

**Issue by itsdapi** [immich-app/immich-charts#206]
Trying to migrate from truenas immich to pure helm deployment, but ran into issues that truenas old helm implementation require to separate the subfolder inside the `upload` to many mount points. I looked into the `server.yaml` file. It will be nice if we could customize the persistent config.

```
persistence:
{{- if .Values.immich.configuration }}
  config:
    enabled: true
    type: configMap
    name: {{ .Release.Name }}-immich-config
{{- end }}
  library:
    enabled: true
    mountPath: /usr/src/app/upload
    existingClaim: {{ .Values.immich.persistence.library.existingClaim }}
{{- end }}
```
