### ISSUE TITLE
Service and Ingress Port not being defined

### ISSUE THREAD

**Issue by FuriousLlama** [immich-app/immich-charts#208]
Hello, I am having an issue trying to deploy the Helm chart on my local k3s instance. I am not an expert, so any assistance would be helpful to get this working.

The installation and upgrades fail with the error at[1]. I checked different values, files but I was not able to get any of them working. [2] contains my current one.

I have traced the issue to the port not being defined when helm generates the resources[3].

My guess is that there is something off with the helm chart that is causing the template of the service to not generate the port. I've tried to manually set it according to the common helm library, but that did not work either. 

Thanks in advance.

[1] Output:

```
$helm upgrade --create-namespace --namespace immich immich oci://ghcr.io/immich-app/immich-charts/immich -f values.yaml
Pulled: ghcr.io/immich-app/immich-charts/immich:0.9.3
Digest: sha256:95e098ffc5f5f1af0c9de09944e13fc367b18960f75cea603e499377b8f006a6
Error: UPGRADE FAILED: failed to create resource: Service "immich" is invalid: spec.ports[0].port: Invalid value: 0: must be between 1 and 65535, inclusive
```

[2]Values file:
```
image:
  # renovate: datasource=github-releases depName=immich-app/immich
  tag: "v1.132.3"

immich:
  metrics:
    # Enabling this will create the service monitors needed to monitor immich with the prometheus operator
    enabled: true
  persistence:
    # Main data store for all photos shared between different components.
    library:
      # Automatically creating the library volume is not supported by this chart
      # You have to specify an existing PVC to use
      existingClaim:
        - name: immich-pvc
          mountPath: /immich

server:
      ingress:
        main:
          enabled: true
          ingressClassName: external
          annotations:
            external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
            nignx.ingress.kubernetes.io/force-ssl-redirect: "true"
            nginx.ingress.kubernetes.io/proxy-body-size: "0"

          hosts:
            - host: &host "photos.${SECRET_DOMAIN}"
              paths:
                - path: /
                  pathType: Prefix
```
[2]Generated template, server section:
```
# Source: immich/templates/server.yaml
apiVersion: v1
kind: Service
metadata:
  name: immich
  labels:
    app.kubernetes.io/service: immich
    app.kubernetes.io/instance: immich
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: immich
    app.kubernetes.io/version: v1.119.0
    helm.sh/chart: immich-0.9.3
  annotations:
spec:
  type: ClusterIP
  ports:
    - port:
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: immich
    app.kubernetes.io/name: immich
