### ISSUE TITLE
Ingress nginx results in long pauses/delays in UI

### ISSUE THREAD

**Issue by CafeLungo** [immich-app/immich-charts#214]
Is there a recommended ingress configuration for nginx? I have tried a few things, but I keep getting long gaps in communication to the UI-- the UI just freezes, can't load anything. I suspect it's some sort of websocket timeout through the ingress, but I can't be sure.

I am using your chart, but running 1.133.1 containers. I had to setup the latest database as well. I just migrated from a docker-compose setup, into kubernetes. So I was already on 1.133.x on docker-compose, so I needed to maintain that when moving into K8s. The database and library migration all went smoothly, but now as I've been using it, I've noticed this problem. I was using Caddy on my docker-compose setup, but now I'm using nginx ingress in K8s.

Here is my current ingress config, but it's not working super well:

```yaml
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: immich-server
  namespace: immich
  annotations:
    cert-manager.io/cluster-issuer: my-issuer
    nginx.ingress.kubernetes.io/proxy-body-size: '0'
    nginx.ingress.kubernetes.io/proxy-read-timeout: 600s
    nginx.ingress.kubernetes.io/proxy-send-timeout: 600s
    nginx.ingress.kubernetes.io/send-timeout: 600s
    nginx.ingress.kubernetes.io/server-snippets: |
      location / {
        # Set headers
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # enable websockets: http://nginx.org/en/docs/http/websocket.html
        proxy_http_version 1.1;
        proxy_set_header   Upgrade    $http_upgrade;
        proxy_set_header   Connection "upgrade";
        proxy_redirect     off;
        }
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - immich.my-network.com
      secretName: immich-my-network-tls
  rules:
    - host: immich.my-network.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: immich-server
                port:
                  number: 2283
```

Thanks for any pointers! BTW, I love this project a lot!
