### ISSUE TITLE
Servicemonitor not working

### ISSUE THREAD

**Issue by steled** [immich-app/immich-charts#222]
Hi,

it seems that the metrics port are not reachable/available:

![Image](https://github.com/user-attachments/assets/facf0255-3c87-488d-841f-3f03b4cdc15d)

```shell
$ k get pods -n immich -owide
NAME                                       READY   STATUS    RESTARTS        AGE     IP           NODE      NOMINATED NODE   READINESS GATES
immich-machine-learning-6986d454c9-6fxhr   1/1     Running   0               5m24s   10.0.1.60    k8s-w01   <none>           <none>
immich-postgresql-0                        1/1     Running   1 (4m52s ago)   5m24s   10.0.0.207   k8s-c01   <none>           <none>
immich-redis-master-0                      1/1     Running   0               5m24s   10.0.1.225   k8s-w01   <none>           <none>
immich-server-b777767bd-bcl9l              1/1     Running   1 (4m53s ago)   5m24s   10.0.1.72    k8s-w01   <none>           <none>

$ k get svc -n immich
NAME                      TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
immich-machine-learning   ClusterIP   10.108.106.44    <none>        3003/TCP                     5m1s
immich-postgresql         ClusterIP   10.101.170.4     <none>        5432/TCP                     5m1s
immich-postgresql-hl      ClusterIP   None             <none>        5432/TCP                     5m1s
immich-redis-headless     ClusterIP   None             <none>        6379/TCP                     5m1s
immich-redis-master       ClusterIP   10.105.193.130   <none>        6379/TCP                     5m1s
immich-server             ClusterIP   10.101.181.9     <none>        2283/TCP,8081/TCP,8082/TCP   5m1s

$ k exec -it -n immich immich-server-b777767bd-bcl9l -- sh
# curl http://10.0.1.72:8081/metrics
curl: (7) Failed to connect to 10.0.1.72 port 8081 after 0 ms: Couldn't connect to server
# curl http://10.0.1.72:8082/metrics
curl: (7) Failed to connect to 10.0.1.72 port 8082 after 0 ms: Couldn't connect to server
# curl http://10.101.181.9:8081/metrics
curl: (7) Failed to connect to 10.101.181.9 port 8081 after 0 ms: Couldn't connect to server
# curl http://10.101.181.9:8082/metrics
curl: (7) Failed to connect to 10.101.181.9 port 8082 after 0 ms: Couldn't connect to server
# curl http://localhost:8081/metrics
curl: (7) Failed to connect to localhost port 8081 after 0 ms: Couldn't connect to server
# curl http://localhost:8082/metrics
curl: (7) Failed to connect to localhost port 8082 after 0 ms: Couldn't connect to server
```

**Comment by steled** [comment]
See my values below:

```yaml
env:
  - name: REDIS_HOSTNAME
    value: immich-redis-master
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: immich-secret
        key: postgresql-user-password
  - name: DB_HOSTNAME
    value: immich-postgresql
  - name: DB_DATABASE_NAME
    value: '<REDACTED>'
  - name: DB_USERNAME
    value: '<REDACTED>'
  - name: IMMICH_MACHINE_LEARNING_URL
    value: http://immich-machine-learning:3003
  - name: TZ
    value: Europe/Berlin
  - name: UPLOAD_LOCATION
    value: /usr/src/app/upload
  - name: IMMICH_MEDIA_LOCATION
    value: /upload

image:
  tag: v1.134.0

immich:
  metrics:
    # Enabling this will create the service monitors needed to monitor immich with the prometheus operator
    enabled: true # currently not working, waiting for a fix: https://github.com/immich-app/immich-charts/issues/222
  persistence:
    # Main data store for all photos shared between different components.
    library:
      # Automatically creating the library volume is not supported by this chart
      # You have to specify an existing PVC to use
      existingClaim: immich-pvc

server:
  ingress:
    main:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: cloudflare-letsencrypt-production
        ingress.cilium.io/loadbalancer-mode: shared
        # proxy-body-size is set to 0 to remove the body limit on file uploads
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
      hosts:
        - host: '<REDACTED>'
          paths:
            - path: "/"
      ingressClassName: cilium
      tls:
        - secretName: immich-tls
          hosts:
            - '<REDACTED>'

machine-learning:
  persistence:
    cache:
      type: pvc
      storageClass: longhorn

useDeprecatedPostgresChart: true

postgresql:
  auth:
    enablePostgresUser: false
  enabled: true
  image:
    repository: tensorchord/vchord-postgres
    tag: pg17-v0.3.0
  backup:
    enabled: true
    cronjob:
      schedule: "@hourly"
      storage:
        enabled: true
        storageClass: longhorn
  primary:
    resourcesPreset: "large"
    containerSecurityContext:
      readOnlyRootFilesystem: false
    
  global:
    defaultStorageClass: longhorn
    postgresql:
      auth:
        database: '<REDACTED>'
        username: '<REDACTED>'
        existingSecret: immich-secret
        secretKeys:
          userPasswordKey: postgresql-user-password

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
```
