### ISSUE TITLE
Add resource limit to machine learning

### ISSUE THREAD

**Issue by Y0ngg4n** [immich-app/immich-charts#30]
It would be nice to limit the resources of the machine learning pod as it can stress the node on which it is running immensely.

**Comment by bo0tzz** [comment]
I considered adding resource requests/limit when I was building the chart, but I decided against it as people have wildly different resource availability and so choosing a 'default' isn't feasible. You can easily add them yourself though:
```yaml
machine-learning:
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
```
