### ISSUE TITLE
Machine Learning CrashLoopBackoff

### ISSUE THREAD

**Issue by Y0ngg4n** [immich-app/immich-charts#37]
I always get a crashloopbackoff with the machinelearning container:
```
INFO:     Started server process [7]
INFO:     Waiting for application startup.
Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
```

**Comment by bo0tzz** [comment]
This might be a duplicate of #27, can you try the suggestion in there?

**Comment by Y0ngg4n** [comment]
@bo0tzz already completely disabled the liveness probe

**Comment by bo0tzz** [comment]
Do you have the cache volume enabled for ML?

**Comment by Y0ngg4n** [comment]
@bo0tzz no

```
machine-learning:
      resources:
        limits:
          cpu: 200m
          memory: 500Mi
      probes:
        liveness:
          enabled: false
          spec:
            initialDelaySeconds: 90
        readiness:
          enabled: false
          spec:
            initialDelaySeconds: 90
        startup:
          enabled: false
          spec:
            initialDelaySeconds: 90
```
