### ISSUE TITLE
[Feature Request] Add additionalVolumeMounts and additionalVolumes

### ISSUE THREAD

**Issue by CygnusHyoga** [immich-app/immich-charts#41]
It would be nice to add AdditionalVolumeMounts and additionalVolumes to the helm chart.

For example for custom CA Certificates for OAUTH authentication (NODE_EXTRA_CA_CERTS=/path/to/your/ CA/cert/file) and for the upcoming PR Feat(server,web): libraries (https://github.com/immich-app/immich/pull/3124)

Thanks!

**Comment by bo0tzz** [comment]
You can already add extra volumes under the `persistence` key for each component. See https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml#L580 and https://bjw-s.github.io/helm-charts/docs/common-library/storage/types/pvc.html for some more detail.

**Comment by CygnusHyoga** [comment]
Thanks it's working!! Here is an example, if anyone is interested on how to mount custom ca certificates on immich server container with trust-manager (cert-manager) certificates.

```yaml
...
server:
  enabled: true
  image:
    repository: ghcr.io/immich-app/immich-server
    tag: v1.78.1
    pullPolicy: IfNotPresent
  persistence:
    ca-certs:
      enabled: true
      name: example.com
      type: configMap
      defaultMode: 420
      mountPath: /etc/ssl/certs/ca-certificates.crt
      subPath: root-certs.pem
...
```
