### ISSUE TITLE
how to set cache to pvc

### ISSUE THREAD

**Issue by pOH7** [immich-app/immich-charts#48]
```
      persistence:
        geodata-cache:
          enabled: true
          size: 1Gi
          # Optional: Set this to pvc to avoid downloading the geodata every start.
          type: emptyDir
          accessMode: ReadWriteMany
          # storageClass: your-class
```
I use kubernetes, it showed "Set this to pvc to avoid downloading the geodata every start.", but I don't know how to, and there is no example

**Comment by bo0tzz** [comment]
If you just set it to `type: pvc` in your values, it will create a new pvc using your default storageClass. You can set `storageClass` to manually choose one. Alternatively you can define a pvc yourself and then use that with
```yaml
persistence:
  geodata-cache:
    enabled: true
    existingClaim: your-pvc
```

**Comment by pOH7** [comment]
> If you just set it to `type: pvc` in your values, it will create a new pvc using your default storageClass. You can set `storageClass` to manually choose one. Alternatively you can define a pvc yourself and then use that with
> 
> ```yaml
> persistence:
>   geodata-cache:
>     enabled: true
>     existingClaim: your-pvc
> ```

thanks, I have tried both, first solution (change type to pvc) works, and the second should be 

```
persistence:
  geodata-cache:
    enabled: true
    type: pvc
    existingClaim: your-pvc
```
