### ISSUE TITLE
How to configure persistence volume for postgres ?

### ISSUE THREAD

**Issue by Emilien-M** [immich-app/immich-charts#56]
Hi,

I would like the intgrate postgres don't use the default storage class for data. How can i configure the release to do that ?

I try this, but the PVC continue tu use default storage class : 

```
postgresql:
  enabled: true
  persistence:
    data:
      enabled: true
      size: 8Gi
      storageClass: my-custom-storage-class
      accessMode: ReadWriteMany
```

**Comment by bo0tzz** [comment]
This chart uses the [bitnami postgres chart](https://artifacthub.io/packages/helm/bitnami/postgresql) as a dependency. You can configure the PVC like so:
```yaml
postgresql:
  enabled: true
  primary:
    persistence:
      size: 8Gi
      storageClass: my-custom-storage-class
```

Note that you should not set accessMode ReadWriteMany for a database volume, as postgres does not support multiple instances using the same data volume.
