### ISSUE TITLE
Image to use with Cloudnative PG

### ISSUE THREAD

**Issue by Rahulsharma0810** [immich-app/immich-charts#60]
I used to host Immich with https://cloudnative-pg.io, Perhaps since vector is a thing I am not able to run Immich with this helm chart. 

```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-immich-cluster
  namespace: cnpg-system
spec:
  imageName: ghcr.io/bo0tzz/cnpgvecto.rs:15
  postgresql:
    shared_preload_libraries:
      - "vectors.so"
  affinity:
    nodeSelector:
      kubernetes.io/hostname: i11806-kube-node-2-03
  instances: 1
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
      storageClassName: manual-immich
  monitoring:
    enablePodMonitor: true
  bootstrap:
    initdb:
      database: postgresql-immich-pgsql
      owner: postgresql-immich-pgsql
      secret:
        name: post-init-immich-pgsql-secret
      postInitTemplateSQL:
        - CREATE EXTENSION IF NOT EXISTS cube;
        - CREATE EXTENSION IF NOT EXISTS earthdistance;
```

immich logs

```
[Nest] 7  - 01/15/2024, 11:13:03 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (3)...
QueryFailedError: permission denied to create extension "vectors"
    at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async assertVectors (/usr/src/app/dist/infra/database.config.js:53:5)
    at async UsePgVectors1700713871511.up (/usr/src/app/dist/infra/migrations/1700713871511-UsePgVectors.js:11:9)
    at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
    at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:260:35)
    at async DataSource.initialize (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:148:17)
[Nest] 7  - 01/15/2024, 11:13:03 PM   ERROR [ExceptionHandler] permission denied to create extension "vectors"
QueryFailedError: permission denied to create extension "vectors"
    at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async assertVectors (/usr/src/app/dist/infra/database.config.js:53:5)
    at async UsePgVectors1700713871511.up (/usr/src/app/dist/infra/migrations/1700713871511-UsePgVectors.js:11:9)
    at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
    at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:260:35)
    at async DataSource.initialize (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:148:17)

```

Has anyone tried this Chart with Cloudnative Pg?
