### ISSUE TITLE
Support providing multiple volumes

### ISSUE THREAD

**Issue by ekulno** [immich-app/immich-charts#70]
Support providing multiple volumes, instead of just a single one as is currently the case. 

Use cases: 
 - A user may have multiple source data volumes, which are infeasible to merge into a single one. 
 - A user may not trust Immich to not modify their existing photo gallery, and wants to provide a read-only volume of existing data in addition to a read-write volume for immich to add new uploads to. 

Both of these use cases apply to me. This blocks me from using Immich.

**Comment by hiteshnayak305** [comment]
@bo0tzz  can we use extra volumes ans external library to achieve this?

**Comment by bo0tzz** [comment]
It's should already be possible to provide extra volumes, eg
```yaml
immich:
  persistence:
    library:
      existingClaim: library-claim
(...)
server:
  persistence:
    external:
      external:
        enabled: true
        existingClaim: external-claim
microservices:
  persistence:
    external:
      external:
        enabled: true
        existingClaim: external-claim
```

**Comment by djjudas21** [comment]
The external libraries wouldn't work in your example, I had to remove the double-indented `external` block. This worked for me:

```yaml
server:
  persistence:
    external:
      enabled: true
      existingClaim: external-claim
      readOnly: true
microservices:
  persistence:
    external:
      enabled: true
      existingClaim: external-claim
      readOnly: true
```
