### ISSUE TITLE
Behaviour of `*-postgresql` secret is undocumented and confusing

### ISSUE THREAD

**Issue by alexbarcelo** [immich-app/immich-charts#8]
I tried to deploy the chart, and noticed that a secret appeared called `immich-postgresql` with two fields called `password` and `postgres-password`.

With that in mind, I succeeded in doing a deployment with mostly defaults with the following additional configuration:
```yaml
common_env:
  DB_PASSWORD: 
    valueFrom:
      secretKeyRef:
        name: immich-postgresql
        key: password
```

However, today I changed the chart deployment (by updating the tag, but I don't think that's rellevant). The immich-server was unable to connect to the database. I suspect that the secret manifest had changed and it broke the connection. My "repair" was to change the `DB_PASSWORD` environment variable and hardcode the original password. However, that was confusing.

I am a n00b chart user so maybe I missed something obvious. I was somewhat expecting the secret thing to be generated on first deployment and be inmutable from that point onwards. I don't k now if that makes sense, or if that behavior may break more stuff. Unfortunately, I don't really know how to do that (otherwise I would try to do the PR myself).
