### ISSUE TITLE
Allow using using existing secret for env 

### ISSUE THREAD

**Issue by p4block** [immich-app/immich-charts#95]
Despite commenting out the recommended setup of using a existingSecret for the postgres subchart, I found no way of using said existing secret for the immich env

**Comment by p4block** [comment]
Well, nothing like posting the issue being the prime factor to encountering the solution.
Diving into the common chart's [values.yaml](https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml) (very interesting, never worked with these before) I saw that this is a supported syntax.

Working great now!

```
 env:
    DB_PASSOWRD:
      valueFrom:
        secretKeyRef:
          name: pg-password
          key: PG_PASSWORD

    REDIS_HOSTNAME: '{{ printf "%s-redis-master" .Release.Name }}'
   (...)
```
