### ISSUE TITLE
Setting Components Affinity

### ISSUE THREAD

**Issue by seang96** [immich-app/immich-charts#96]
I am trying to set the affinity based off of the common library but it seems to not be working properly. I got replicas working by specifying it under controller for the deployment, and according to the library it should be specified under pod object of the controller. See my snippet below for server component.

```
server:
  enabled: true
  controller:
    replicas: 2
    pod:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/instance: immich
                  app.kubernetes.io/name: server
              topologyKey: "kubernetes.io/hostname"
```
